name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Update apt cache and enable repositories
      run: |
        sudo apt-get update
        sudo add-apt-repository universe
        sudo add-apt-repository multiverse
        sudo apt-get update

    - name: Install dependencies
      run: |
        sudo apt-get install -y \
          libimlib2-dev \
          libx11-dev \
          libxft-dev \
          libfreetype6-dev \
          libfontconfig1-dev \
          libgif-dev \
          libexif-dev
    - name: make
      run: make
