name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: dependencies
      run: sudo apt-get update &&
           sudo apt install -y \
           libimlib2-dev \
           libx11-dev \
           libxft-dev \
           libfreetype6-dev \
           libfontconfig1-dev \
           libgif-dev \
           libexif-dev
    - name: make
      run: make
